### ISSUE TITLE
please add support orange pi one plus (H6)

### ISSUE THREAD

**Issue by efirshik** [adafruit/Adafruit_CircuitPython_SSD1306#65] opened 2021-06-04 10:24 UTC
this gpio pinout
![1](https://user-images.githubusercontent.com/43796942/120787485-76676b00-c540-11eb-99a2-fb6473c65b4f.jpg)
![2](https://user-images.githubusercontent.com/43796942/120787498-79625b80-c540-11eb-90fe-a01ef12c0592.png)

python3 ssd1306_stats.py 
`Traceback (most recent call last):
  File "ssd1306_stats.py", line 12, in <module>
    from board import SCL, SDA
  File "/usr/local/lib/python3.7/dist-packages/board.py", line 254, in <module>
    platform.system(), package[0], package[1]
NotImplementedError: Adafruit-PlatformDetect version 3.13.3 was unable to identify the board and/or microcontroller running the Linux platform. Please be sure you have the latest packages running: 'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'`

pip list | grep -i adafruit
`Adafruit-Blinka                  6.10.0
adafruit-circuitpython-busdevice 5.0.6
adafruit-circuitpython-framebuf  1.4.7
adafruit-circuitpython-ssd1306   2.11.4
Adafruit-GPIO                    1.0.4
Adafruit-PlatformDetect          3.13.3
Adafruit-PureIO                  1.1.8
adafruit-python-shell            1.3.1
Adafruit-SSD1306                 1.6.2
`

**Comment by ladyada** [comment] 2021-06-04 14:18
hi - this is a duplicate of https://github.com/adafruit/Adafruit_Blinka/issues/481
stick to one issue please

**Closed as completed by ladyada** 2021-06-04 14:18 UTC
